"""Add user_id to persons

Revision ID: 094bc601f6ae
Revises: 7eb0870a9950
Create Date: 2025-11-17 15:51:23.290514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094bc601f6ae'
down_revision: Union[str, Sequence[str], None] = '7eb0870a9950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'persons', ['user_id'])
    op.create_foreign_key(None, 'persons', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_constraint(None, 'persons', type_='unique')
    op.drop_column('persons', 'user_id')
    # ### end Alembic commands ###
