"""Added lead_substage field to leads table

Revision ID: 0d65c8d40fbb
Revises: 36e1c046655c
Create Date: 2025-12-13 17:44:41.466544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d65c8d40fbb'
down_revision: Union[str, Sequence[str], None] = '36e1c046655c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_substage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'lead_substage')
    # ### end Alembic commands ###
