"""Add affiliate link and lead attribution to installs

Revision ID: 1257fbc45959
Revises: 2499b8667e82
Create Date: 2025-12-16 16:52:46.666230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1257fbc45959'
down_revision: Union[str, Sequence[str], None] = '2499b8667e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=False),
    sa.Column('tracking_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_links_affiliate_user_id'), 'affiliate_links', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_id'), 'affiliate_links', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_tracking_url'), 'affiliate_links', ['tracking_url'], unique=True)
    op.add_column('affiliate_installs', sa.Column('affiliate_link_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('affiliate_installs', sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=True))
    op.alter_column('affiliate_installs', 'affiliate_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('affiliate_installs', 'shop_domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('affiliate_installs', 'client_account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_affiliate_installs_affiliate_link_id'), 'affiliate_installs', ['affiliate_link_id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_lead_id'), 'affiliate_installs', ['lead_id'], unique=False)
    op.create_foreign_key(None, 'affiliate_installs', 'affiliate_links', ['affiliate_link_id'], ['id'])
    op.create_foreign_key(None, 'affiliate_installs', 'leads', ['lead_id'], ['id'])
   # op.alter_column('leads', 'created_by',
   #            existing_type=sa.VARCHAR(),
   #            type_=sa.UUID(),
   #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#   op.alter_column('leads', 'created_by',
#               existing_type=sa.UUID(),
#               type_=sa.VARCHAR(),
#               existing_nullable=True)
    op.drop_constraint(None, 'affiliate_installs', type_='foreignkey')
    op.drop_constraint(None, 'affiliate_installs', type_='foreignkey')
    op.drop_index(op.f('ix_affiliate_installs_lead_id'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_affiliate_link_id'), table_name='affiliate_installs')
    op.alter_column('affiliate_installs', 'client_account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('affiliate_installs', 'shop_domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('affiliate_installs', 'affiliate_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('affiliate_installs', 'lead_id')
    op.drop_column('affiliate_installs', 'affiliate_link_id')
    op.drop_index(op.f('ix_affiliate_links_tracking_url'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_id'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_affiliate_user_id'), table_name='affiliate_links')
    op.drop_table('affiliate_links')
    # ### end Alembic commands ###
