"""Flatten lead details fields

Revision ID: 13771bc77ba6
Revises: 78fff1ae349c
Create Date: 2025-11-24 22:03:45.327665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13771bc77ba6'
down_revision: Union[str, Sequence[str], None] = '78fff1ae349c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_details', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('lead_details', sa.Column('twitter_url', sa.String(length=255), nullable=True))
    op.add_column('lead_details', sa.Column('instagram_url', sa.String(length=255), nullable=True))
    op.add_column('lead_details', sa.Column('full_address', sa.String(length=255), nullable=True))
    op.drop_column('lead_details', 'addresses')
    op.drop_column('lead_details', 'social_links')
    op.alter_column('lead_notes', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'lead_notes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_notes', type_='foreignkey')
    op.alter_column('lead_notes', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('lead_details', sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('lead_details', sa.Column('addresses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('lead_details', 'full_address')
    op.drop_column('lead_details', 'instagram_url')
    op.drop_column('lead_details', 'twitter_url')
    op.drop_column('lead_details', 'linkedin_url')
    # ### end Alembic commands ###
