"""Add score field to leads table

Revision ID: 36e1c046655c
Revises: 9cfcda687b20
Create Date: 2025-12-13 16:06:25.307029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e1c046655c'
down_revision: Union[str, Sequence[str], None] = '9cfcda687b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('score', sa.Integer(), nullable=True))
    op.alter_column('leads', 'industry',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'industry',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('leads', 'score')
    # ### end Alembic commands ###
