"""Add affiliate_link_id to leads

Revision ID: 38f5d5f835d6
Revises: 1257fbc45959
Create Date: 2025-12-16 19:55:11.283650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f5d5f835d6'
down_revision: Union[str, Sequence[str], None] = '1257fbc45959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('affiliate_link_id', sa.UUID(), nullable=True))
    # op.alter_column('leads', 'created_by',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    op.create_index(op.f('ix_leads_affiliate_link_id'), 'leads', ['affiliate_link_id'], unique=False)
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'affiliate_links', ['affiliate_link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_affiliate_link_id'), table_name='leads')
    # op.alter_column('leads', 'created_by',
    #           existing_type=sa.UUID(),
    #           type_=sa.VARCHAR(),
    #           existing_nullable=True)
    op.drop_column('leads', 'affiliate_link_id')
    # ### end Alembic commands ###
