"""Add affiliate tracking tables

Revision ID: 3bf5ebaed249
Revises: abb27c9e3b04
Create Date: 2025-12-08 08:52:12.955323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf5ebaed249'
down_revision: Union[str, Sequence[str], None] = 'abb27c9e3b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_affiliate_user_id'), 'affiliate_clicks', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_id'), 'affiliate_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_shop_domain'), 'affiliate_clicks', ['shop_domain'], unique=False)
    op.create_table('affiliate_installs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('client_account_id', sa.UUID(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affiliate_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_installs_affiliate_user_id'), 'affiliate_installs', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_client_account_id'), 'affiliate_installs', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_id'), 'affiliate_installs', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_shop_domain'), 'affiliate_installs', ['shop_domain'], unique=False)
    op.create_table('affiliate_referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('last_click_id', sa.UUID(), nullable=True),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_click_id'], ['affiliate_clicks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_referrals_affiliate_user_id'), 'affiliate_referrals', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_affiliate_referrals_id'), 'affiliate_referrals', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_referrals_shop_domain'), 'affiliate_referrals', ['shop_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_referrals_shop_domain'), table_name='affiliate_referrals')
    op.drop_index(op.f('ix_affiliate_referrals_id'), table_name='affiliate_referrals')
    op.drop_index(op.f('ix_affiliate_referrals_affiliate_user_id'), table_name='affiliate_referrals')
    op.drop_table('affiliate_referrals')
    op.drop_index(op.f('ix_affiliate_installs_shop_domain'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_id'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_client_account_id'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_affiliate_user_id'), table_name='affiliate_installs')
    op.drop_table('affiliate_installs')
    op.drop_index(op.f('ix_affiliate_clicks_shop_domain'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_affiliate_user_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    # ### end Alembic commands ###
