"""update leads fields

Revision ID: 414bb5d3f423
Revises: 13771bc77ba6
Create Date: 2025-12-04 20:26:14.605580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414bb5d3f423'
down_revision: Union[str, Sequence[str], None] = '13771bc77ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_details', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('lead_details', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('priority', sa.String(length=50), nullable=True))
    op.drop_column('leads', 'platform')
    op.drop_column('leads', 'entry_point')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('entry_point', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('platform', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('leads', 'priority')
    op.drop_column('leads', 'source')
    op.drop_column('lead_details', 'tags')
    op.drop_column('lead_details', 'job_title')
    # ### end Alembic commands ###
