"""update accounts model

Revision ID: 419da88d10f0
Revises: 20db1b3b204f
Create Date: 2025-11-20 16:37:05.007716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '419da88d10f0'
down_revision: Union[str, Sequence[str], None] = '20db1b3b204f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('accounts', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('accounts', sa.Column('founded_date', sa.Date(), nullable=True))
    op.add_column('accounts', sa.Column('annual_revenue', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('full_address', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('twitter_url', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('instagram_url', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('account_type', sa.String(length=100), nullable=False))
    op.add_column('accounts', sa.Column('client_type', sa.String(length=100), nullable=False))
    op.add_column('accounts', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('accounts', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('segment', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('territory', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('accounts', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('accounts', sa.Column('owner_name', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('is_subsidiary', sa.Boolean(), nullable=True))
    op.add_column('accounts', sa.Column('is_child_account', sa.Boolean(), nullable=True))
    op.add_column('accounts', sa.Column('last_activity_date', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('total_revenue', sa.String(length=255), nullable=True))
    op.alter_column('accounts', 'phone_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_column('accounts', 'legal_details')
    op.drop_column('accounts', 'affiliate_type')
    op.drop_column('accounts', 'address')
    op.drop_column('accounts', 'social_links')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'phone_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('users_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_id_key'), 'users', ['id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'phone_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('accounts', sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('address', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('affiliate_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('legal_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('accounts', 'phone_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('accounts', 'total_revenue')
    op.drop_column('accounts', 'last_activity_date')
    op.drop_column('accounts', 'is_child_account')
    op.drop_column('accounts', 'is_subsidiary')
    op.drop_column('accounts', 'owner_name')
    op.drop_column('accounts', 'owner_id')
    op.drop_column('accounts', 'tags')
    op.drop_column('accounts', 'source')
    op.drop_column('accounts', 'territory')
    op.drop_column('accounts', 'segment')
    op.drop_column('accounts', 'priority')
    op.drop_column('accounts', 'status')
    op.drop_column('accounts', 'client_type')
    op.drop_column('accounts', 'account_type')
    op.drop_column('accounts', 'instagram_url')
    op.drop_column('accounts', 'twitter_url')
    op.drop_column('accounts', 'linkedin_url')
    op.drop_column('accounts', 'full_address')
    op.drop_column('accounts', 'location')
    op.drop_column('accounts', 'annual_revenue')
    op.drop_column('accounts', 'founded_date')
    op.drop_column('accounts', 'description')
    op.drop_column('accounts', 'company_size')
    op.drop_column('accounts', 'logo_url')
    op.drop_column('accounts', 'company_name')
    # ### end Alembic commands ###
