"""initial demo schema

Revision ID: 5067587f2f00
Revises: 
Create Date: 2026-01-02 10:24:12.136508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5067587f2f00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('price_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('reason_lost', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('phone_code', sa.String(length=20), nullable=True),
    sa.Column('phone_no', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('annual_revenue', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('full_address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_code', sa.String(length=20), nullable=True),
    sa.Column('phone_no', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=100), nullable=False),
    sa.Column('client_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('territory', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('is_subsidiary', sa.Boolean(), nullable=True),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('is_child_account', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('total_revenue', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_shop_domain'), 'accounts', ['shop_domain'], unique=True)
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_affiliate_user_id'), 'affiliate_clicks', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_id'), 'affiliate_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_shop_domain'), 'affiliate_clicks', ['shop_domain'], unique=False)
    op.create_table('affiliate_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=False),
    sa.Column('tracking_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_links_affiliate_user_id'), 'affiliate_links', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_id'), 'affiliate_links', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_tracking_url'), 'affiliate_links', ['tracking_url'], unique=True)
    op.create_table('opportunity_products',
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('personality_type', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('affiliate_referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('last_click_id', sa.UUID(), nullable=True),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_click_id'], ['affiliate_clicks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_referrals_affiliate_user_id'), 'affiliate_referrals', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_affiliate_referrals_id'), 'affiliate_referrals', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_referrals_shop_domain'), 'affiliate_referrals', ['shop_domain'], unique=False)
    op.create_table('commission_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'canceled', name='commissionstatus'), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['salesperson_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_records_id'), 'commission_records', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_code', sa.String(length=10), nullable=True),
    sa.Column('phone_no', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('entry_point', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('lead_stage', sa.String(), nullable=True),
    sa.Column('lead_substage', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_contact', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('affiliate_link_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_link_id'], ['affiliate_links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_affiliate_link_id'), 'leads', ['affiliate_link_id'], unique=False)
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_table('opportunity_persons',
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], )
    )
    op.create_table('performance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=True),
    sa.Column('total_opportunities', sa.Integer(), nullable=True),
    sa.Column('closed_deals', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('total_commission', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_persons',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_payout_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lifetime_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lifetime_withdrawals', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_person_id'), 'wallets', ['person_id'], unique=False)
    op.create_table('affiliate_installs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=True),
    sa.Column('affiliate_link_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('shop_domain', sa.String(length=255), nullable=True),
    sa.Column('client_account_id', sa.UUID(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affiliate_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_link_id'], ['affiliate_links.id'], ),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_installs_affiliate_link_id'), 'affiliate_installs', ['affiliate_link_id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_affiliate_user_id'), 'affiliate_installs', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_client_account_id'), 'affiliate_installs', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_id'), 'affiliate_installs', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_lead_id'), 'affiliate_installs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_affiliate_installs_shop_domain'), 'affiliate_installs', ['shop_domain'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CALL', 'EMAIL', 'MESSAGE', 'MEETING', 'FOLLOW_UP', 'DEMO', 'NOTE', 'OTHER', name='interactiontype'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_table('lead_accounts',
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], )
    )
    op.create_table('lead_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('legal_details', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('full_address', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('interest_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_leads',
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], )
    )
    op.create_table('person_leads',
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], )
    )
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('withdrawal_status_enum', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'PROCESSING', 'COMPLETED', name='withdrawalstatus'), nullable=False),
    sa.Column('payout_method_enum', sa.Enum('PAYPAL', 'BANK_TRANSFER', name='payoutmethod'), nullable=False),
    sa.Column('bank_account_holder_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('paypal_email', sa.String(length=255), nullable=True),
    sa.Column('admin_comments', sa.String(length=500), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_index(op.f('ix_withdrawal_requests_id'), 'withdrawal_requests', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_requested_by_id'), 'withdrawal_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_wallet_id'), 'withdrawal_requests', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_withdrawal_status_enum'), 'withdrawal_requests', ['withdrawal_status_enum'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('poc_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['poc_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type_enum', sa.Enum('COMMISSION_CREDIT', 'WITHDRAWAL_REQUESTED', 'WITHDRAWAL_COMPLETED', 'WITHDRAWAL_REJECTED', 'ADJUSTMENT_CREDIT', 'ADJUSTMENT_DEBIT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('related_withdrawal_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['related_withdrawal_id'], ['withdrawal_requests.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_related_withdrawal_id'), 'wallet_transactions', ['related_withdrawal_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_transaction_type_enum'), 'wallet_transactions', ['transaction_type_enum'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('followup_assignees',
    sa.Column('followup_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['followup_id'], ['followups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('followup_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followup_assignees')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_transaction_type_enum'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_related_withdrawal_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_withdrawal_requests_withdrawal_status_enum'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_wallet_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_requested_by_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_table('person_leads')
    op.drop_table('opportunity_leads')
    op.drop_table('lead_products')
    op.drop_table('lead_notes')
    op.drop_table('lead_details')
    op.drop_table('lead_accounts')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_affiliate_installs_shop_domain'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_lead_id'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_id'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_client_account_id'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_affiliate_user_id'), table_name='affiliate_installs')
    op.drop_index(op.f('ix_affiliate_installs_affiliate_link_id'), table_name='affiliate_installs')
    op.drop_table('affiliate_installs')
    op.drop_index(op.f('ix_wallets_person_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('product_persons')
    op.drop_table('performance_records')
    op.drop_table('opportunity_persons')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_affiliate_link_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_commission_records_id'), table_name='commission_records')
    op.drop_table('commission_records')
    op.drop_index(op.f('ix_affiliate_referrals_shop_domain'), table_name='affiliate_referrals')
    op.drop_index(op.f('ix_affiliate_referrals_id'), table_name='affiliate_referrals')
    op.drop_index(op.f('ix_affiliate_referrals_affiliate_user_id'), table_name='affiliate_referrals')
    op.drop_table('affiliate_referrals')
    op.drop_table('persons')
    op.drop_table('opportunity_products')
    op.drop_index(op.f('ix_affiliate_links_tracking_url'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_id'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_affiliate_user_id'), table_name='affiliate_links')
    op.drop_table('affiliate_links')
    op.drop_index(op.f('ix_affiliate_clicks_shop_domain'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_affiliate_user_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.drop_index(op.f('ix_accounts_shop_domain'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
