"""Add nullable shop_domain to accounts

Revision ID: 50afc31329ff
Revises: 3bf5ebaed249
Create Date: 2025-12-08 10:05:13.918871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50afc31329ff'
down_revision: Union[str, Sequence[str], None] = '3bf5ebaed249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('shop_domain', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_accounts_shop_domain'), 'accounts', ['shop_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_shop_domain'), table_name='accounts')
    op.drop_column('accounts', 'shop_domain')
    # ### end Alembic commands ###
