"""Added last_contacted_at field to leadstable & updated status default to new

Revision ID: 70c90a98003d
Revises: 0d65c8d40fbb
Create Date: 2025-12-15 12:43:28.404868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c90a98003d'
down_revision: Union[str, Sequence[str], None] = '0d65c8d40fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_contacted_at')
    # ### end Alembic commands ###
