"""restore lead_accounts m2m table

Revision ID: 78fff1ae349c
Revises: 419da88d10f0
Create Date: 2025-11-21 13:50:24.324128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fff1ae349c'
down_revision: Union[str, Sequence[str], None] = '419da88d10f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'accounts', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.alter_column('accounts', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
