"""change last_contacted_at to last_contact_at

Revision ID: 7ac134c0adc7
Revises: 70c90a98003d
Create Date: 2025-12-15 13:05:57.162359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ac134c0adc7'
down_revision: Union[str, Sequence[str], None] = '70c90a98003d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('leads', 'last_contacted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_contacted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('leads', 'last_contact_at')
    # ### end Alembic commands ###
