"""Add is_deleted to Wallet

Revision ID: 7eb0870a9950
Revises: d4e8dff4dcb0
Create Date: 2025-11-17 14:51:08.053363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb0870a9950'
down_revision: Union[str, Sequence[str], None] = 'd4e8dff4dcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['id'])
    op.add_column('wallets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'is_deleted')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
