"""add entry_point back to leads

Revision ID: e78ea2e7c841
Revises: 414bb5d3f423
Create Date: 2025-12-05 08:59:29.581281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e78ea2e7c841'
down_revision: Union[str, Sequence[str], None] = '414bb5d3f423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_clicks_affiliate_user_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_shop_admin'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.add_column('leads', sa.Column('entry_point', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'entry_point')
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shop_admin', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('utm_source', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], name=op.f('affiliate_clicks_affiliate_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('affiliate_clicks_pkey'))
    )
    op.create_index(op.f('ix_affiliate_clicks_shop_admin'), 'affiliate_clicks', ['shop_admin'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_id'), 'affiliate_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_affiliate_user_id'), 'affiliate_clicks', ['affiliate_user_id'], unique=False)
    # ### end Alembic commands ###
