"""Added is_contact column to leads table, corresponding response in schemas,and updated service for convert_lead_to_contact

Revision ID: fa45fde16d4a
Revises: 50afc31329ff
Create Date: 2025-12-09 13:26:33.911637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa45fde16d4a'
down_revision: Union[str, Sequence[str], None] = '50afc31329ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('is_contact', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'is_contact')
    # ### end Alembic commands ###
